### PR TITLE
Split out the guts into Test::Sync

### PR DESCRIPTION
**Pull request by exodist**
This is what it would look like if I split the dist into Test-Sync (the core sync stuff needed by both Test::Stream and Test::Builder) and Test-Stream (my stuff built on top of it)

### CODE REVIEW

**Comment by exodist** [comment]
So, I am gonna kick off a discussion here:

First order of business: Are there modules here that should be removed? I personally do not think it would be reasonable to take anything else out.

Second order of business: Are there modules that should be in here that I did not bring over?

Third: I decided to adopt a new namespace for these guts to convey what they actually are. They are the synchronization code that allows test tools and frameworks (such as Test::Builder, and Test::Stream) to all work together. This also gave me the freedom to remove the deprecation's that result from the tap_rework branch. It also means that any file can still be renamed or have its API changed, I can bear the compatibility burden in the Test::Stream::* namespaces for a while.

**Comment by kentfredric** [comment]
I would personally like a better name than "Sync" however, that name seems far too vague and generic for what you're doing.

These are the internals, the guts that powers the new infrastructure, no? Maybe a name like "Core" something that communicates its *centrality*

**Comment by exodist** [comment]
Test::Core, Test::Base, Test::Builder and 1 or 2 others that came to mind were all taken.

**Comment by kentfredric** [comment]
`Test::Wheel` appeals to me for a whole bunch of reasons right now. 

`Test::Wheel::Hub`  *smirk*

**Comment by exodist** [comment]
Closing as I want to re-open after some more cleanup, and picking a name,

**Pull request closed without merging**
